spring:
  application:
    name: price
  profiles:
    active:
    - local
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'